# Generated by Django 2.2 on 2020-03-03 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_auto_20200303_1740'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRaceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver1_points_qualification', models.IntegerField(default=0)),
                ('driver2_points_qualification', models.IntegerField(default=0)),
                ('team1_points_qualification', models.IntegerField(default=0)),
                ('team2_points_qualification', models.IntegerField(default=0)),
                ('driver1_points_race', models.IntegerField(default=0)),
                ('driver2_points_race', models.IntegerField(default=0)),
                ('team1_points_race', models.IntegerField(default=0)),
                ('team2_points_race', models.IntegerField(default=0)),
                ('total_points_before', models.IntegerField(default=0, help_text='Total points before this race')),
                ('total_points_after', models.IntegerField(default=0, help_text='Total points after this race, so race points and extra points in total')),
                ('total_points_race', models.IntegerField(default=0, help_text='Points for drivers and teams')),
                ('total_points_extra', models.IntegerField(default=0, help_text='Points for fastest questions and trivia')),
                ('driver1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_result_driver1', to='game.Driver')),
                ('driver2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_result_driver2', to='game.Driver')),
                ('fastest_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_result_fastest_driver', to='game.Driver')),
                ('fastest_pit_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_result_fastest_pit_stop', to='game.Team')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_race_results', to='game.Race')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_result_team1', to='game.Team')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_result_team2', to='game.Team')),
                ('trivia_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_result_answer', to='game.TriviaAnswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_race_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RaceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joker_driver1', models.BooleanField(default=False)),
                ('joker_driver2', models.BooleanField(default=False)),
                ('joker_team1', models.BooleanField(default=False)),
                ('joker_team2', models.BooleanField(default=False)),
                ('driver1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_profile_driver1', to='game.Driver')),
                ('driver2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_profile_driver2', to='game.Driver')),
                ('fastest_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_profile_fastest_driver', to='game.Driver')),
                ('fastest_pit_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_profile_fastest_pit_stop', to='game.Team')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_profile_team1', to='game.Team')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_profile_team2', to='game.Team')),
                ('trivia_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_profile_answer', to='game.TriviaAnswer')),
            ],
        ),
    ]
