# Generated by Django 2.2 on 2020-03-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('driver', 'Driver'), ('motor', 'Motor')], max_length=20)),
                ('race_type', models.CharField(choices=[('qualification', 'Qualification'), ('race', 'Race')], max_length=20)),
                ('result', models.IntegerField()),
                ('points', models.IntegerField()),
                ('extra_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=128)),
                ('answer_1', models.CharField(max_length=25)),
                ('answer_2', models.CharField(max_length=25)),
                ('answer_3', models.CharField(max_length=25)),
                ('answer_4', models.CharField(max_length=25)),
                ('correct_answer', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trivia', to='game.Race')),
            ],
        ),
        migrations.CreateModel(
            name='TeamProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_value', models.IntegerField()),
                ('end_value', models.IntegerField(null=True)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='game.Team')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_progresses', to='game.Race')),
            ],
        ),
        migrations.CreateModel(
            name='DriverProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_value', models.IntegerField()),
                ('end_value', models.IntegerField(null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='game.Driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_progresses', to='game.Race')),
            ],
        ),
        migrations.CreateModel(
            name='DriverResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_qualification', models.IntegerField()),
                ('result_race', models.IntegerField()),
                ('fastest_lap', models.BooleanField(default=False)),
                ('drive_through', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.Driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.Race')),
            ],
            options={
                'unique_together': {('driver', 'race')},
            },
        ),
    ]
