# Generated by Django 2.2 on 2020-03-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200301_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trivia',
            old_name='questions',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='answer_4',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='correct_answer',
        ),
        migrations.CreateModel(
            name='TriviaAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=128)),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.Trivia')),
            ],
        ),
    ]
