# Generated by Django 2.2 on 2020-03-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200303_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='race',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
    ]
