# Generated by Django 2.2 on 2020-03-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200305_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
