# Generated by Django 2.2 on 2020-03-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_driver_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True, help_text='When a driver is not active for a race, this is to disable him'),
        ),
    ]
