# Generated by Django 2.2 on 2020-03-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_driver_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='number',
            field=models.IntegerField(default=1, help_text='Field to indicate the order of the teams'),
            preserve_default=False,
        ),
    ]
