# Generated by Django 2.2 on 2020-03-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_team_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='number',
            new_name='order',
        ),
        migrations.AddField(
            model_name='driver',
            name='order',
            field=models.IntegerField(default=1, help_text='Field to indicate the order of the drivers within a team'),
            preserve_default=False,
        ),
    ]
