# Generated by Django 2.2 on 2020-03-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200306_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='The year the race started')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='game.Season'),
        ),
        migrations.AddField(
            model_name='race',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='game.Season'),
        ),
        migrations.AddField(
            model_name='team',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='game.Season'),
        ),
    ]
